version: "3.8"

services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    env_file:
      - .env
    user: "${PUID}:${PGID}"
    volumes:
      - /srv/downloads:/srv
      - ./filebrowser_data:/database

    networks:
      - proxy
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.sametak.com`)"
    - "traefik.http.routers.filebrowser.entrypoints=https"
    - "traefik.http.routers.filebrowser.tls.certresolver=cloudflare"
    - "traefik.http.services.filebrowser.loadbalancer.server.port=80"

      # Servis

networks:
  proxy:
    external: true
