services:
  portainer:
    image: portainer/portainer-ce:2.21.4
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${PORTAINER_FRONTEND_DOMAIN}`)"
      - "traefik.http.routers.frontend.entrypoints=https"
      - "traefik.http.services.frontend.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend.service=frontend"
      - "traefik.http.routers.frontend.tls.certresolver=cloudflare"

      # Edge
      - "traefik.http.routers.edge.rule=Host(`${PORTAINER_EDGE_DOMAIN}`)"
      - "traefik.http.routers.edge.entrypoints=https"
      - "traefik.http.services.edge.loadbalancer.server.port=8000"
      - "traefik.http.routers.edge.service=edge"
      - "traefik.http.routers.edge.tls.certresolver=cloudflare"
    env_file:
      - .env
    networks:
      - proxy

volumes:
  portainer_data:

networks:
  proxy:
    external: true
